export { Speedometer, SPEEDOMETER_VARIANTS } from "./components/speedometer/Speedometer"
export type { SpeedometerProps, SpeedometerVariant } from "./components/speedometer/types"
export { Compass } from "./components/compass/Compass"
export { Altitude } from "./components/altitude/Altitude"
export { GForce } from "./components/g-force/GForce"
export { Timer } from "./components/timer/Timer"
export { CircuitMap } from "./components/circuit-map/CircuitMap"
export { LapTimer } from "./components/lap-timer/LapTimer"

export { registerWidget, getWidget, getAllWidgets, getWidgetsByCategory } from "./registry/widgetRegistry"
export type { WidgetMeta, WidgetRenderer } from "./registry/widgetRegistry"
export { registerDefaultWidgets } from "./registry/defaultWidgets"

export { useWidgetTelemetry } from "./hooks/useWidgetTelemetry"
export { ExportModeProvider, useExportMode } from "./contexts/ExportModeContext"
