import type { Template } from "@velocity/shared"

export const goProStyle: Template = {
  id: "gopro-style",
  name: "GoPro Style",
  description: "Full telemetry overlay with speed, altitude, compass, and G-force.",
  category: "gopro",
  tags: ["gopro", "action", "full-telemetry"],
  style: {
    primaryColor: "#1EAEFD",
    secondaryColor: "#ffffff",
    fontFamily: "system-ui",
    theme: "dark",
  },
  widgets: [
    {
      id: "w-speed-1",
      type: "speedometer",
      x: 40,
      y: 820,
      width: 160,
      height: 160,
      rotation: 0,
      scale: 1,
      opacity: 0.95,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "scale",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#1EAEFD" },
    },
    {
      id: "w-altitude-1",
      type: "altitude",
      x: 220,
      y: 860,
      width: 140,
      height: 60,
      rotation: 0,
      scale: 1,
      opacity: 0.95,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "slide-up",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#4488ff" },
    },
    {
      id: "w-compass-1",
      type: "compass",
      x: 1720,
      y: 840,
      width: 120,
      height: 120,
      rotation: 0,
      scale: 1,
      opacity: 0.95,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#1EAEFD" },
    },
    {
      id: "w-gforce-1",
      type: "g-force",
      x: 1720,
      y: 680,
      width: 120,
      height: 120,
      rotation: 0,
      scale: 1,
      opacity: 0.9,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#ff4444" },
    },
  ],
}
