import type { Template } from "@velocity/shared"

export const minimalCinematic: Template = {
  id: "minimal-cinematic",
  name: "Minimal Cinematic",
  description: "Clean, understated overlay for cinematic footage. Speed + timer only.",
  category: "minimal",
  tags: ["minimal", "cinematic", "clean"],
  style: {
    primaryColor: "#00ff88",
    secondaryColor: "#4488ff",
    fontFamily: "system-ui",
    theme: "dark",
  },
  widgets: [
    {
      id: "w-speed-1",
      type: "speedometer",
      x: 40,
      y: 880,
      width: 140,
      height: 140,
      rotation: 0,
      scale: 1,
      opacity: 0.92,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "glass", accentColor: "#00ff88" },
    },
    {
      id: "w-timer-1",
      type: "timer",
      x: 200,
      y: 930,
      width: 180,
      height: 48,
      rotation: 0,
      scale: 1,
      opacity: 0.9,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "glass", accentColor: "#00ff88" },
    },
  ],
}
