import type { Template } from "@velocity/shared"

export const racingStyle: Template = {
  id: "racing-style",
  name: "Racing Style",
  description: "High-performance overlay with prominent speed, G-force, and lap timer.",
  category: "racing",
  tags: ["racing", "motorsport", "performance"],
  style: {
    primaryColor: "#ff3300",
    secondaryColor: "#ffcc00",
    fontFamily: "system-ui",
    theme: "dark",
  },
  widgets: [
    {
      id: "w-speed-1",
      type: "speedometer",
      x: 880,
      y: 860,
      width: 200,
      height: 200,
      rotation: 0,
      scale: 1,
      opacity: 1,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "scale",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#ff3300" },
    },
    {
      id: "w-gforce-1",
      type: "g-force",
      x: 1700,
      y: 40,
      width: 160,
      height: 160,
      rotation: 0,
      scale: 1,
      opacity: 1,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#ff3300" },
    },
    {
      id: "w-timer-1",
      type: "timer",
      x: 760,
      y: 40,
      width: 220,
      height: 56,
      rotation: 0,
      scale: 1,
      opacity: 1,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "slide-down",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#ffcc00" },
    },
    {
      id: "w-compass-1",
      type: "compass",
      x: 40,
      y: 40,
      width: 120,
      height: 120,
      rotation: 0,
      scale: 1,
      opacity: 0.9,
      zIndex: 10,
      visible: true,
      locked: false,
      animationIn: "fade",
      animationOut: "fade",
      style: { theme: "dark", accentColor: "#ff3300" },
    },
  ],
}
